---
title: "Silo-Mito Visualizer"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}

### The application is split into different code chunks. In this chunk, general settings are defined while libraries and files required for the application are loaded. Variables are defined in the global.R file in the same folder. The subsequent chunks are split into two different sets, one for SILO and the other for MITO, each having 3 code chunks. The first chunk of each set creates a sidebar for user input and sources the file containing the server logic. The second chunk creates a map or a plot while the third creates a table related to the map or plot. The logics are defined in different R scripts and they are referred to accordingly.


# increase the size limit of uploaded files
options(shiny.maxRequestSize = 30*1024^2)

default_implementation = "kgw"
#choose between mstm or muc or kgw

parameters_muc = list(zone_filename = "../map/muc/zones_31468.shp",
                      base_year = 2011,
                      final_year = 2050)
parameters_mstm = list(zone_filename = "../map/mstm/zones_mstm_100026_clean.shp",
                       base_year = 2000,
                       final_year = 2005)

parameters_kgw = list(zone_filename = "../map/kgw/zones_KGW.shp",
                       base_year = 2010,
                       final_year = 2050)

parameters_ct = list(zone_filename = "../map/ct/zones_ct.shp",
                       base_year = 2011,
                       final_year = 2040)


parameters = list(muc = parameters_muc, mstm = parameters_mstm, kgw=parameters_kgw, ct = parameters_ct)




zone_filename = parameters[[default_implementation]]$zone_filename 
base_year = parameters[[default_implementation]]$base_year
final_year = parameters[[default_implementation]]$final_year

# load required libraries

library(readr) #for reading in data
library(readxl) #for reading excel files
library(sf) #for handling spatial data
library(zoo) #for manipulating data frames
library(plyr) #for recoding datag by mapping old- and new-name pairs
library(dplyr) #for manipulating data
library(stringr) #for manipulating strings
library(tidyr) #for tidying data
library(DT) #for producing interactive tables
library(plotly) #for producing interactive plots
library(tmap) #for producing maps
library(leaflet) #for producing interactive maps
library(viridis) #for picking colors
library(RColorBrewer) #for picking colors


# source required files
source("fileReader.R", local = TRUE) #contains module for reading files
source("siloSpecific/siloSidebar.R", local = TRUE) #contains code for creating a sidebar for silo visualization
source("mitoSpecific/mitoSidebar.R", local = TRUE) #contains code for creating a sidebar for mito visualization
source("dataPreparation.R", local = TRUE) #contains code for cleaning data
source("figureTableFunctions.R", local = TRUE) #contains functions for creating plots, maps and tables


# create colors
msmQualitative <- brewer.pal(12, "Set3")[c(1, 3:12)] #colors used for qualitative attributes
msmSequential <- viridisLite::viridis(10, direction = -1) #colors used for sequential attributes
msmPastel <- brewer.pal(9, "Pastel1") #colors used for pie chart


# read in zones shapefile and labels file
zones <- st_read(zone_filename) #zone file needed for spatial representation
myLabels <- read_excel("visualizerLabels.xlsx") # labels file for appropriate labeling of plots

```

SILO
=======================================================================

Column {.sidebar data-width=400}
-----------------------------------------------------------------------


```{r}

# create panels for taking silo user input (refer to siloSidebar.R)
siloFileUploadPanel
siloDataTypeSelectorPanel
siloAttributeSelectorPanel


# intermediary logic for creating silo outputs
source("siloSpecific/siloLogicFunctions.R", local = TRUE) # functions used in the reactives
source("siloSpecific/siloLogic.R", local = TRUE) #reactives for subsetting selected sito attribute

```



Column {data-width=800 .tabset}
-----------------------------------------------------------------------

### Figure

```{r}

# display the selected silo attribute in a plot or map
uiOutput("siloFigure")


# create plots and label them
source("siloSpecific/siloFigureCreation.R", local = TRUE) 


# select the kind of graphical representation to use based on the selected silo attribute
output$siloFigure <- renderUI({
  if(input$siloDataType == "Aspatial"){
    plotlyOutput("siloPlot")
  } else {
    leafletOutput("siloMap")
  }
})

```


### Table

```{r}

# display table associated with the selected silo attribute
DT::dataTableOutput("siloTable")


# create tables and add headers
source("siloSpecific/siloTableCreation.R", local = TRUE) 

```


MITO
=======================================================================

Column {.sidebar data-width=400}
-----------------------------------------------------------------------


```{r}

# create panels for taking mito user input (refer to mitoSidebar.R)
mitoFileUploadPanel
mitoDataTypeSelectorPanel
mitoAttributeSelectorPanel


# intermediary logic for creating mito outputs
source("mitoSpecific/mitoLogic.R", local = TRUE) #reactives and functions for subsetting selected mito attribute

```


Column {data-width=800 .tabset}
-----------------------------------------------------------------------

### Figure

```{r}

# display the selected mito attribute in a plot or map
uiOutput("mitoFigure")


# create plots and label them
source("mitoSpecific/mitoFigureCreation.R", local = TRUE)


# select the kind of graphical representation to use based on the selected mito attribute
output$mitoFigure <- renderUI({
  if(input$mitoDataType == "Aspatial"){
    plotlyOutput("mitoPlot")
  } else {
    leafletOutput("mitoMap")
  }
})

```


### Table

```{r}

# display table associated with the selected mito attribute
DT::dataTableOutput("mitoTable")


# create tables and add headers
source("mitoSpecific/mitoTableCreation.R", local = TRUE) 

```


